CREATE TABLE IF NOT EXISTS users(
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	account VARCHAR(20) NOT NULL,
	password VARCHAR(255) NOT NULL,
	name VARCHAR(10) NOT NULL,
	branch_id INTEGER NOT NULL,
	department_id INTEGER NOT NULL,
	is_stopped INTEGER NOT NULL DEFAULT 0,
	created_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS messages(
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(30) NOT NULL,
	main_text TEXT NOT NULL,
	category VARCHAR(10) NOT NULL,
	user_id INTEGER NOT NULL,
	created_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);